// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreinandoCodinDojo.Data;

#nullable disable

namespace TreinandoCodinDojo.Migrations
{
    [DbContext(typeof(CodinContext))]
    partial class CodinContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CollaboratorProject", b =>
                {
                    b.Property<int>("CollaboratorsId")
                        .HasColumnType("int");

                    b.Property<int>("Projectsid")
                        .HasColumnType("int");

                    b.HasKey("CollaboratorsId", "Projectsid");

                    b.HasIndex("Projectsid");

                    b.ToTable("CollaboratorProject");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.ApproveHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApproveHours");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ApproveHoursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("Modality")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproveHoursId");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.TimeRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ApproveHoursId")
                        .HasColumnType("int");

                    b.Property<int>("CollaboratorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproveHoursId");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("CollaboratorProject", b =>
                {
                    b.HasOne("TreinandoCodinDojo.Models.Collaborator", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreinandoCodinDojo.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("Projectsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.Collaborator", b =>
                {
                    b.HasOne("TreinandoCodinDojo.Models.ApproveHours", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ApproveHoursId");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.TimeRecording", b =>
                {
                    b.HasOne("TreinandoCodinDojo.Models.ApproveHours", null)
                        .WithMany("Records")
                        .HasForeignKey("ApproveHoursId");

                    b.HasOne("TreinandoCodinDojo.Models.Collaborator", "Collaborator")
                        .WithMany("RegisteredHours")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreinandoCodinDojo.Models.Project", "Project")
                        .WithMany("RegisteredHours")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.ApproveHours", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.Collaborator", b =>
                {
                    b.Navigation("RegisteredHours");
                });

            modelBuilder.Entity("TreinandoCodinDojo.Models.Project", b =>
                {
                    b.Navigation("RegisteredHours");
                });
#pragma warning restore 612, 618
        }
    }
}
